## 端口号  上下文路径
server:
  port: 8090
  servlet:
    context-path: /SeckillSystem

spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sxfcds2100340
    password: SX_fcds2100340
    url: jdbc:mysql://172.31.32.231:3306/sxfcds2100340?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  #redis
  redis:
    host: 172.31.38.144
    port: 6379
    database: 0
    password: Wzjdkd959!

#rocketMq配置
rocketmq:
  name-server: 172.31.38.144
  producer:
    group: seckill-producer
    retry-times-when-send-async-failed: 2
    send-message-timeout: 3000


#mybatis配置
mybatis:
  type-aliases-package: com.fuchuang.seckillsystem.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #下划线变成大写
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志信息 日志级别为mapper层
logging:
  level:
    com:
      wu:
        mapper: debug
  file:
    name: seckill.log
    path: /seckill/logs

#jwt配置
jwt:
  secret: ffjaksdfjak #私钥 自己可以自由发挥
  expiration: 3600000 #过期时间 一个小时
  header: token #自己往请求头部放的名字
  refresh_expiration: 651000000 #刷新token的过期时间7天


#限制ip访问次数
request:
  expireTime: 2
  count: 5

#sm4加密密钥
sm4:
  key: 1937492387465927

#规则文件所在本地目录
rules:
  filePath: /seckill/rules/
